version: 2

sources:
  - name: sus_pipeline
    database: awsdatacatalog
    schema: sus_pipeline
    tables:
      - name: sih_sp
        description: "Dados brutos do SIH/DATASUS - internações hospitalares SP"
      - name: cnes_estabelecimentos
        description: "Dados brutos do CNES - estabelecimentos de saúde SP"