version: 2

sources:
  - name: sus_pipeline
    database: awsdatacatalog
    schema: sus_pipeline
    tables:
      - name: sih_sp
        description: "Dados brutos do SIH/DATASUS - internações hospitalares SP"
      - name: cnes_estabelecimentos
        description: "Dados brutos do CNES - estabelecimentos de saúde SP"
      - name: sim_obitos
        description: "Dados brutos do SIM - óbitos SP"
      - name: raas_psicossocial
        description: "Dados brutos do RAAS - atendimentos psicossociais SP"
      - name: censo_populacao
        description: "Censo 2022 - população total por município SP"
      - name: censo_raca_cor
        description: "Censo 2022 - população por raça/cor por município SP"
      - name: censo_instrucao
        description: "Censo 2022 - nível de instrução por município SP"
      - name: censo_favelas
        description: "Censo 2022 - domicílios em favelas por município SP"
      - name: ibge_populacao_estimada
        description: "Estimativas populacionais IBGE por município SP 2015-2024"